### ISSUE TITLE
Please, add example with sys::furi_message_queue_get

### ISSUE THREAD

**Issue by UndeRus** [dcoles/flipperzero-rs#14]
I tried to reproduce this example https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/examples/example_images/example_images.c , but can't get returned FuriStatusOk(or other value in bindings) in while loop

```
        let mut running = true;
        let mut event: sys::InputEvent = sys::InputEvent {
            sequence: 0,
            key: 0,
            type_: 0,
        };

        let event_ptr: *mut c_void = &mut event as *mut _ as *mut c_void;

        while running == true {
            if sys::furi_message_queue_get(event_queue, event_ptr, 100) == sys::FuriStatus_FuriStatusOk {
                println!("Event: {:?}", event);
                running = false;
                if (event.type_ == sys::InputType_InputTypePress) || (event.type_ == sys::InputType_InputTypeRepeat) {

                    println!("Event: {:?}", event);
                    match event.key {
                        sys::InputKey_InputKeyBack => {
                            running = false;
                            break;
                        }
                        _ => {
                            running = false;
                        }
                    }
                }
            }
        }
```

**Comment by dcoles** [comment]
Hi @UndeRus,

It's a bit hard to tell exactly why your code isn't working without being able to see the `app_input_callback` and code to initialize the message queue. But here's a version of [`example_images`](https://github.com/dcoles/flipperzero-rs/blob/main/crates/flipperzero/examples/example_images.rs) that I managed to get working.

Make sure you use [flipperzero-sys-0.3.1](https://crates.io/crates/flipperzero-sys/0.3.1) or newer, as this fixes an issue in the bindings where enums like `InputKey` and `InputType` were the incorrect size.
